version: '3.8'

services:
  app:
    container_name: smartclinic-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3332:80"  # A porta externa 3332 redireciona para a porta 80 do container
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production